foreground         #c2c6c5
background         #0c1c1a
background_opacity 1.0
cursor             #c2c6c5

active_tab_foreground     #0c1c1a
active_tab_background     #c2c6c5
inactive_tab_foreground   #c2c6c5
inactive_tab_background   #0c1c1a

active_border_color   #c2c6c5
inactive_border_color #0c1c1a
bell_border_color     #244b4e

color0       #0c1c1a
color8       #5b706e
color1       #244b4e
color9       #306569
color2       #3f484d
color10      #546067
color3       #3b5458
color11      #4F7076
color4       #485c63
color12      #617B84
color5       #466066
color13      #5E8188
color6       #566062
color14      #738083
color7       #8f9998
color15      #c2c6c5
