# Hardware acceleration & Wayland video output
hwdec=auto-safe
vo=gpu-next
gpu-context=wayland

# High quality rendering
profile=high-quality
scale=ewa_lanczos
cscale=ewa_lanczos

video-sync=display-resample
interpolation=yes
tscale=oversample

# Subtitle configuration
slang=eng,en,enUS
alang=jpn,ja,eng,en
sub-auto=fuzzy
save-position-on-quit=yes

# Customize Status Message
# term-status-msg="\x1b[1;36m[${time-pos} / ${duration} (${percent-pos}%)]\x1b[0m \x1b[1;32m[${video-format} ${video-params/w}x${video-params/h} @ ${estimated-vf-fps}fps | ${hwdec-current}]\x1b[0m \x1b[1;33m[V-Bit: ${video-bitrate} | A-Bit: ${audio-bitrate}]\x1b[0m \x1b[1;35m[A/V Sync: ${avsync}]\x1b[0m \x1b[1;31m[Dropped: ${frame-drop-count}]\x1b[0m \x1b[1;34m[Cache: ${demuxer-cache-duration:0}s]\x1b[0m \x1b[1;37m[Vol: ${volume}%]\x1b[0m"
term-status-msg="\x1b[1;36m${time-pos}/${duration}\x1b[0m \x1b[1;32m[${video-format} ${video-params/w}x${video-params/h}]\x1b[0m \x1b[1;33m${video-bitrate:0}\x1b[0m \x1b[1;35m${avsync}\x1b[0m \x1b[1;31mDrop:${frame-drop-count}\x1b[0m \x1b[1;34mBuf:${demuxer-cache-duration:0}s\x1b[0m"

# Force rich stats to print inside the Kitty terminal window
term-osd-bar=yes
term-osd-bar-chars="━╸━  "  # Uses smooth Nerd Font progress bars
term-playing-msg="Playing: ${filename} [Resolution: ${video-params/w}x${video-params/w}]"

